name: CI - Integração Contínua

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v4

      - name: Configurar Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Instalar dependências
        run: npm ci

      - name: Executar lint
        run: npm run lint || echo "Lint não configurado"

      - name: Executar testes
        run: npm test || echo "Testes não configurados"

      - name: Verificar build
        run: npm run build

      - name: Armazenar artefato de build
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: build/
